builds:
  - binary: cfparams
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64

checksum:
  name_template: "checksums.txt"

archives:
  - format: "binary"
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  use: github-native
  sort: asc
  filters:
    exclude:
      - "^build:"
      - "^ci:"
      - "^docs:"
      - "^test:"

brews:
  - name: cfparams
    tap:
      owner: cultureamp
      name: homebrew-tap
    commit_author:
      name: cultureamp-ci
      email: 36431315+cultureamp-ci@users.noreply.github.com

    folder: Formula
    homepage: https://github.com/cultureamp/cfparams
    description: Wrangle parameters for AWS CloudFormation

    test: |
      minimal = testpath/"minimal.yaml"
      minimal.write <<~EOS
        Parameters:
          TestParameter:
            Type: String
            Default: testvalue
        Resources:
          S3Bucket:
            Type: AWS::S3::Bucket
      EOS
      system "#{bin}/cfparams --template=minimal.yaml"
    install: |
      bin.install "cfparams_{{ .Os }}_{{ .Arch }}" => "cfparams"

# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
