builds:
  - binary: cfparams
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64

checksum:
  name_template: "checksums.txt"

archives:
  - format: "binary"
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  use: github-native
# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
