version: 2

builds:
  - binary: cfparams
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64

checksum:
  name_template: "checksums.txt"

archives:
  - formats: [binary]
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  use: github-native
  sort: asc
  filters:
    exclude:
      - "^build:"
      - "^ci:"
      - "^docs:"
      - "^test:"

release:
  mode: replace

homebrew_casks:
  - name: cfparams
    repository:
      owner: cultureamp
      name: homebrew-tap
      token: "{{ .Env.GITHUB_HOMEBREW_TAP_TOKEN }}"
    commit_author:
      name: "{{ .Env.RELEASE_USERNAME }}"
      email: "{{ .Env.RELEASE_EMAIL }}"

    homepage: https://github.com/cultureamp/cfparams
    description: Wrangle parameters for AWS CloudFormation

# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
