services:
  git-cliff:
    # use latest label as versioned labels aren't published
    image: orhunp/git-cliff:latest
    volumes:
      - .:/workspace
    working_dir: /workspace
    environment:
      - GITHUB_TOKEN
      - RELEASE_USERNAME
      - RELEASE_EMAIL

  goreleaser:
    image: goreleaser/goreleaser:v2.15.2
    volumes:
      - .:/workspace
    working_dir: /workspace
    environment:
      - GITHUB_TOKEN
      - GITHUB_HOMEBREW_TAP_TOKEN
      - RELEASE_USERNAME
      - RELEASE_EMAIL
