steps:
  - block: "Release build"
    branches:
      - main
    fields:
      - select: "Prerelease?"
        key: "release-type"
        options:
          - label: "Stable"
            value: "stable"
          - label: "Alpha"
            value: "alpha"
          - label: "Beta"
            value: "beta"
        required: true
        default: "stable"
      - text: "Version number"
        key: "release-version"
        hint: "(optional) forced version (X.X.X)"
        required: false

  - label: ":github: Trigger release"
    branches:
      - main
    command: "bin/ci_trigger_release"
    agents:
      queue: ${BUILD_AGENT}-v6
    plugins:
      - cultureamp/aws-assume-role:
          role: ${BUILD_ROLE}
          duration: 900 # limit role assumption validity to 15 minutes
      - cultureamp/aws-sm#v2.2.0:
          env:
            GITHUB_TOKEN: /cfparams/GITHUB_TOKEN

notify:
  - slack:
      channels:
        - "#team_sre_foundations_alerts"
      message: ":fyii: <!subteam^S03CQLT3G2J>: A new version of CFParams is ready to be released :shipit:"
    if: 'build.branch == "main" && build.state == "blocked"'
