steps:
  - block: "Release build"
    branches:
      - main
    fields:
      - select: "Prerelease?"
        key: "release-type"
        options:
          - label: "Stable"
            value: "stable"
          - label: "Alpha"
            value: "alpha"
          - label: "Beta"
            value: "beta"
        required: true
        default: "stable"
      - text: "Version number"
        key: "release-version"
        hint: "(optional) forced version (X.X.X)"
        required: false

  - label: ":calculator: Calculate version"
    branches:
      - main
    command: "bin/ci_calculate_version"
    agents:
      queue: ${BUILD_AGENT}
    plugins:
      - chinmina/chinmina-token#v1.3.0:
          environment:
            - GITHUB_TOKEN=pipeline:default

  - label: ":git: Create tag"
    branches:
      - main
    command: "bin/ci_create_tag"
    agents:
      queue: ${BUILD_AGENT}
    plugins:
      - chinmina/chinmina-token#v1.3.0:
          environment:
            - GITHUB_TOKEN=pipeline:binary-release

  - label: ":rocket: Release"
    branches:
      - main
    command: "bin/ci_goreleaser"
    agents:
      queue: ${BUILD_AGENT}
    plugins:
      - chinmina/chinmina-token#v1.3.0:
          environment:
            - GITHUB_TOKEN=pipeline:binary-release
            - GITHUB_HOMEBREW_TAP_TOKEN=org:homebrew-tap-publish

notify:
  - slack:
      channels:
        - "#team_sre_foundations_alerts"
      message: ":fyii: <!subteam^S03CQLT3G2J>: A new version of CFParams is ready to be released :shipit:"
    if: 'build.branch == "main" && build.state == "blocked"'
